language: go
go:
- 1.8
- 1.9
- master
os:
- linux
before_install:
- sudo add-apt-repository ppa:masterminds/glide -y
- sudo apt-get update -q
- sudo apt-get install glide -y
- git config --global url."https://github.com/".insteadOf 'git@github.com:'
install:
- export GOBIN="$GOPATH/bin"
- export PATH="$PATH:$GOBIN"
- make install
script:
- export GOBIN="$GOPATH/bin"
- export PATH="$PATH:$GOBIN"
- make test
deploy:
  provider: releases
  api_key:
    secure: gsOhKZ38bSqb4vkNzPfT0rmCAQls78TQhtF2sbL2DMSnXl6sKM0bHkGnMtpqoWrjUtGfxRMD18OAdMWBFGJPjIZXY5yxSifXru+JJuJy3lCaT+SDaa7wEHpz9hUw3CljBuShLQ4pTQZChT3kyc16BAwoRUnbRr0Mq+OOlNbrzq7W3wDdNBZKcfopKS5m7tHWBjoBatEHlrIJacjJhASIHOuj7IxKbgFYB6Js+Ac76WngEYNVD41R9axQij8dSdqGzXdrWpZ0rpf4GW7ooptI/rkkmi21SHBibx3D8ArWTu5YLzQ6tpwZYFhzeULljstfh1wSqupm/w10t3RDTxlUeaPSZwkohrJHmfB2W8pWzoR4fIChD7OK1aRhpW76nY3fVPCQxnIr87aBFp1yRoD2MCaJ7ZwtpDm9yg2o7QVDvFS4MYJ5Kuk1S1c2KDSuOTNPxiDs7g6cSc4Pfdjf/gXiSoWloM2pIlNUQBmCbUj5XscAkBST/5fUwSHC2guBV9oa09GTguDXYnX7e2TbdiIWT3KNR1aGwUmp3er6I0ryLRIDe4nVsVkgYHLHJhuINfN+1e6Wbr4dL+T89oXoRZEh2/T3D0EgTIOcvW7rtj9DiqVP/ylUbn+832bxen8P7PyfRMYosuY+Uyg5Lbv5vRAqLli+Thdc0hyaJjrZy/a85bw=
  file: "$GOBIN/codon"
  on:
    repo: flowgen/go-codon
